// frontend-vue/src/pages/CountryDetail.vue
<template>
  <div class="country-detail">
    <div v-if="country" class="detail-container">
      <!-- Header Section -->
      <div class="detail-header">
        <div class="flag-section">
          <img 
            :src="`https://flagcdn.com/w640/${country.countryCode.toLowerCase()}.png`"
            :alt="`${country.countryName} flag`"
            class="flag-large"
            @error="handleImageError"
          />
        </div>
        <div class="header-info">
          <h1>{{ country.countryName }}</h1>
          <p class="country-code">{{ country.countryCode }}</p>
        </div>
      </div>

      <!-- Key Stats Grid -->
      <div class="stats-grid">
        <div class="stat-box">
          <span class="stat-label">Population</span>
          <span class="stat-value">{{ formatNumber(country.population) }}</span>
        </div>
        <div class="stat-box">
          <span class="stat-label">Area</span>
          <span class="stat-value">{{ formatDecimal(country.areaSqKm) }} km²</span>
        </div>
        <div class="stat-box">
          <span class="stat-label">Density</span>
          <span class="stat-value">{{ formatDecimal(country.populationDensity) }}/km²</span>
        </div>
        <div class="stat-box">
          <span class="stat-label">GDP per Capita</span>
          <span class="stat-value">${{ formatDecimal(country.gdpPerCapita) }}</span>
        </div>
        <div class="stat-box">
          <span class="stat-label">Life Expectancy</span>
          <span class="stat-value">{{ country.lifeExpectancy.toFixed(1) }} years</span>
        </div>
        <div class="stat-box">
          <span class="stat-label">Continent</span>
          <router-link :to="`/continent/${country.continent}`">
            {{ country.continent }}
          </router-link>
        </div>
      </div>

      <!-- Detailed Information -->
      <div class="info-section">
        <h2>Information</h2>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Country Code</span>
            <span class="info-value">{{ country.countryCode }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Year</span>
            <span class="info-value">{{ country.year }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Population</span>
            <span class="info-value">{{ formatNumber(country.population) }} people</span>
          </div>
          <div class="info-item">
            <span class="info-label">Area</span>
            <span class="info-value">{{ formatDecimal(country.areaSqKm) }} km²</span>
          </div>
          <div class="info-item">
            <span class="info-label">Population Density</span>
            <span class="info-value">{{ formatDecimal(country.populationDensity) }} people/km²</span>
          </div>
          <div class="info-item">
            <span class="info-label">GDP per Capita</span>
            <span class="info-value">${{ formatDecimal(country.gdpPerCapita) }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Life Expectancy</span>
            <span class="info-value">{{ formatDecimal(country.lifeExpectancy) }} years</span>
          </div>
          <div class="info-item">
            <span class="info-label">Continent</span>
            <span class="info-value">{{ country.continent }}</span>
          </div>
        </div>
      </div>

      <!-- Population Growth Chart -->
      <div class="chart-section">
        <h2>Population Trend (2018-2023)</h2>
        <div class="chart-container" v-if="populationHistory.length > 0">
          <div class="simple-chart">
            <div v-for="(entry, idx) in populationHistory" :key="idx" class="chart-bar-group">
              <div class="chart-bar">
                <div 
                  class="bar" 
                  :style="{ height: (entry.population / maxPopulation * 100) + '%' }"
                ></div>
              </div>
              <span class="year-label">{{ entry.year }}</span>
            </div>
          </div>
          <div class="chart-legend">
            <p>Population values ({{ formatNumber(maxPopulation) }} at peak)</p>
          </div>
        </div>
      </div>

      <!-- Back Button -->
      <div class="back-button">
        <router-link to="/dashboard">← Back to Dashboard</router-link>
      </div>
    </div>
    <div v-else class="loading">
      Loading country details...
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import api from '../services/api'

const route = useRoute()
const country = ref(null)
const populationHistory = ref([])
const maxPopulation = ref(0)

onMounted(() => {
  const countryCode = route.params.countryCode
  fetchCountryDetail(countryCode)
  fetchPopulationHistory(countryCode)
})

const fetchCountryDetail = async (code) => {
  try {
    const response = await api.get(`/api/population/countries/${code}`)
    country.value = response.data
  } catch (error) {
    console.error('Error fetching country details:', error)
  }
}

const fetchPopulationHistory = async (code) => {
  try {
    const response = await api.get(`/api/population/history/${code}`)
    populationHistory.value = response.data
    maxPopulation.value = Math.max(...populationHistory.value.map(e => e.population))
  } catch (error) {
    console.error('Error fetching population history:', error)
  }
}

const formatNumber = (num) => {
  if (!num) return '0'
  return num.toLocaleString('en-US')
}

const formatDecimal = (num) => {
  if (!num) return '0'
  return num.toLocaleString('en-US', { maximumFractionDigits: 2 })
}

const handleImageError = (event) => {
  event.target.style.display = 'none'
}
</script>

<style scoped>
.country-detail {
  max-width: 1200px;
  margin: 0 auto;
}

.detail-container {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.detail-header {
  display: grid;
  grid-template-columns: 250px 1fr;
  gap: 2rem;
  align-items: center;
  margin-bottom: 1rem;
}

.flag-section {
  display: flex;
  align-items: center;
  justify-content: center;
}

.flag-large {
  width: 250px;
  height: auto;
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.37);
}

.header-info h1 {
  font-size: 2.5rem;
  margin-bottom: 0.5rem;
  color: white;
}

.country-code {
  color: var(--text-secondary);
  font-size: 1rem;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.stat-box {
  background-color: rgba(30, 41, 59, 0.7);
  backdrop-filter: blur(12px);
  border: 1px solid var(--border-color);
  border-radius: 16px;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.stat-label {
  color: var(--text-secondary);
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.stat-value {
  font-size: 1.5rem;
  font-weight: 900;
  color: var(--primary);
}

.stat-box a {
  color: var(--primary);
  text-decoration: none;
}

.stat-box a:hover {
  color: var(--primary-light);
}

.info-section {
  background-color: rgba(30, 41, 59, 0.7);
  backdrop-filter: blur(12px);
  border: 1px solid var(--border-color);
  border-radius: 16px;
  padding: 2rem;
  margin-bottom: 2rem;
}

.info-section h2 {
  margin-bottom: 1.5rem;
  color: white;
}

.info-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1rem;
}

.info-item {
  padding: 1rem;
  background-color: rgba(15, 23, 42, 0.5);
  border-radius: 8px;
  border: 1px solid var(--border-color-light);
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.info-label {
  color: var(--text-secondary);
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.info-value {
  color: var(--text-primary);
  font-size: 0.95rem;
  font-weight: 600;
}

.chart-section {
  background-color: rgba(30, 41, 59, 0.7);
  backdrop-filter: blur(12px);
  border: 1px solid var(--border-color);
  border-radius: 16px;
  padding: 2rem;
  margin-bottom: 2rem;
}

.chart-section h2 {
  margin-bottom: 1.5rem;
  color: white;
}

.chart-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.simple-chart {
  display: flex;
  justify-content: space-around;
  align-items: flex-end;
  height: 300px;
  gap: 0.5rem;
  padding: 1rem 0;
  border-bottom: 2px solid var(--border-color);
}

.chart-bar-group {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
  flex: 1;
}

.chart-bar {
  width: 100%;
  max-width: 60px;
  height: 280px;
  background-color: rgba(15, 23, 42, 0.5);
  border: 1px solid var(--border-color);
  border-radius: 8px 8px 0 0;
  overflow: hidden;
  display: flex;
  align-items: flex-end;
}

.bar {
  width: 100%;
  background: linear-gradient(180deg, var(--primary) 0%, var(--secondary) 100%);
  transition: all 0.3s ease;
}

.bar:hover {
  filter: brightness(1.2);
}

.year-label {
  font-size: 0.75rem;
  color: var(--text-secondary);
  font-weight: 600;
}

.chart-legend {
  text-align: center;
  color: var(--text-secondary);
  font-size: 0.875rem;
}

.back-button {
  margin-top: 2rem;
}

.back-button a {
  display: inline-block;
  padding: 0.75rem 1.5rem;
  background-color: rgba(99, 102, 241, 0.1);
  border: 1px solid var(--primary);
  color: var(--primary);
  border-radius: 8px;
  text-decoration: none;
  transition: all 0.2s ease;
}

.back-button a:hover {
  background-color: var(--primary);
  color: white;
}

.loading {
  text-align: center;
  padding: 4rem 2rem;
  color: var(--text-secondary);
}

@media (max-width: 768px) {
  .detail-header {
    grid-template-columns: 1fr;
    gap: 1rem;
  }

  .flag-large {
    width: 100%;
    max-width: 300px;
  }

  .header-info h1 {
    font-size: 1.75rem;
  }
}
</style>

// frontend/src/pages/CountryDetail.jsx
import { Box, Button, Card, CardContent, Chip, Container, Grid, LinearProgress, Typography } from "@mui/material";
import { motion } from "framer-motion";
import { Activity, ArrowLeft, DollarSign, Heart, Map as MapIcon, Maximize, Newspaper, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer, XAxis, YAxis } from "recharts";
import ImageWithFallback from "../components/ImageWithFallback";
import api from "../services/api";

export default function CountryDetail() {
	const { countryCode } = useParams();
	const [country, setCountry] = useState(null);
	const [history, setHistory] = useState([]);
	const [news, setNews] = useState([]);
	const [loading, setLoading] = useState(true);

	useEffect(() => {
		fetchCountryData();
	}, [countryCode]);

	const fetchCountryData = async () => {
		setLoading(true);
		try {
			const [countryRes, historyRes] = await Promise.all([
				api.get(`/api/population/countries/${countryCode}`),
				api.get(`/api/population/history/${countryCode}`),
			]);

			setCountry(countryRes.data);
			setHistory(historyRes.data);

			try {
				const newsRes = await api.get(`/api/news/country/${countryRes.data.countryName}`);
				setNews(newsRes.data);
			} catch (newsErr) {
				console.error("News fetch failed:", newsErr);
			}
		} catch (error) {
			console.error("Error fetching country detail:", error);
		} finally {
			setLoading(false);
		}
	};

	if (loading) {
		return (
			<Box
				sx={{
					display: "flex",
					justifyContent: "center",
					alignItems: "center",
					minHeight: "60vh",
				}}
			>
				<LinearProgress sx={{ width: "200px", borderRadius: 2 }} />
			</Box>
		);
	}

	if (!country) return <Typography color="white">Country not found.</Typography>;

	return (
		<Container maxWidth="xl" component={motion.div} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
			<Button
				component={Link}
				to="/dashboard"
				startIcon={<ArrowLeft size={16} />}
				sx={{
					mb: 6,
					mt: 2,
					color: "text.secondary",
					fontWeight: 800,
					"&:hover": { color: "white", bgcolor: "rgba(255,255,255,0.05)" },
				}}
			>
				Return to Command Center
			</Button>

			{/* Header Section */}
			<Card
				sx={{
					mb: 8,
					p: { xs: 4, md: 6 },
					borderRadius: 10,
					position: "relative",
					overflow: "hidden",
				}}
			>
				<Box
					sx={{
						position: "absolute",
						top: 0,
						left: 0,
						width: "100%",
						height: "100%",
						background: "linear-gradient(135deg, rgba(99,102,241,0.1) 0%, transparent 100%)",
						zIndex: 0,
					}}
				/>
				<Grid container spacing={8} alignItems="center" sx={{ position: "relative", zIndex: 1 }}>
					<Grid item xs={12} md={5} lg={4}>
						<Box
							sx={{
								position: "relative",
								overflow: "hidden",
								borderRadius: 6,
								boxShadow: "0 24px 48px rgba(0,0,0,0.5)",
								border: "1px solid rgba(255,255,255,0.1)",
							}}
						>
							<ImageWithFallback
								src={`https://flagcdn.com/w640/${country.countryCode.toLowerCase()}.png`}
								fallbackSrc="https://via.placeholder.com/640x400?text=Flag"
								alt={`${country.countryName} flag`}
								style={{ width: "100%", display: "block" }}
							/>
						</Box>
					</Grid>
					<Grid item xs={12} md={7} lg={8}>
						<Chip
							label={country.continent}
							icon={<MapIcon size={12} />}
							sx={{
								mb: 3,
								fontWeight: 900,
								textTransform: "uppercase",
								letterSpacing: "0.1em",
								fontSize: "0.625rem",
								bgcolor: "rgba(99, 102, 241, 0.1)",
								color: "primary.light",
								border: "1px solid rgba(99, 102, 241, 0.2)",
								"& .MuiChip-icon": { color: "inherit" },
							}}
						/>
						<Typography
							variant="h1"
							sx={{
								fontSize: { xs: "3rem", md: "5rem" },
								color: "white",
								mb: 1,
							}}
						>
							{country.countryName}
						</Typography>
						<Typography
							sx={{
								fontSize: "2rem",
								fontWeight: 900,
								color: "text.secondary",
								letterSpacing: "0.2em",
								fontFamily: "monospace",
							}}
						>
							{country.countryCode}
						</Typography>
					</Grid>
				</Grid>
			</Card>

			{/* Stats Grid */}
			<Grid container spacing={4} sx={{ mb: 8 }}>
				{[
					{
						label: "Population",
						value: country.population.toLocaleString(),
						unit: "Citizens",
						icon: Users,
						color: "#6366f1",
						bg: "rgba(99, 102, 241, 0.1)",
					},
					{
						label: "Land Area",
						value: country.areaSqKm.toLocaleString(),
						unit: "sq km",
						icon: Maximize,
						color: "#10b981",
						bg: "rgba(16, 185, 129, 0.1)",
					},
					{
						label: "Density",
						value: country.populationDensity.toFixed(2),
						unit: "p/km²",
						icon: Activity,
						color: "#f59e0b",
						bg: "rgba(245, 158, 11, 0.1)",
					},
					{
						label: "Economy (GDP)",
						value: `$${country.gdpPerCapita.toLocaleString()}`,
						unit: "per capita",
						icon: DollarSign,
						color: "#a855f7",
						bg: "rgba(168, 85, 247, 0.1)",
					},
					{
						label: "Longevity",
						value: country.lifeExpectancy.toFixed(1),
						unit: "years",
						icon: Heart,
						color: "#f43f5e",
						bg: "rgba(244, 63, 94, 0.1)",
					},
				].map((stat) => (
					<Grid item xs={12} sm={6} md={2.4} key={stat.label}>
						<Card sx={{ height: "100%" }}>
							<CardContent sx={{ p: 3 }}>
								<Box
									sx={{
										width: 44,
										height: 44,
										borderRadius: 3,
										bgcolor: stat.bg,
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										mb: 3,
									}}
								>
									<stat.icon size={20} color={stat.color} />
								</Box>
								<Typography variant="h5" sx={{ fontWeight: 900, color: "white", mb: 0.5 }}>
									{stat.value}
								</Typography>
								<Typography
									variant="overline"
									sx={{
										display: "block",
										color: "text.secondary",
										fontWeight: 800,
										lineHeight: 1.2,
									}}
								>
									{stat.label}
								</Typography>
								<Typography
									variant="caption"
									sx={{
										color: "text.disabled",
										fontWeight: 700,
										textTransform: "uppercase",
									}}
								>
									{stat.unit}
								</Typography>
							</CardContent>
						</Card>
					</Grid>
				))}
			</Grid>

			{/* Chart and News */}
			<Grid container spacing={6} sx={{ mb: 8 }}>
				<Grid item xs={12} lg={8}>
					<Card sx={{ p: { xs: 4, md: 6 }, borderRadius: 8 }}>
						<Box
							sx={{
								display: "flex",
								justifyContent: "space-between",
								alignItems: "center",
								mb: 6,
							}}
						>
							<Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
								<Box
									sx={{
										p: 1,
										borderRadius: 2,
										bgcolor: "rgba(99, 102, 241, 0.2)",
										display: "flex",
									}}
								>
									<Activity size={20} color="#818cf8" />
								</Box>
								<Typography variant="h6" sx={{ fontWeight: 800 }}>
									Population Chronology
								</Typography>
							</Box>
							<Typography
								variant="caption"
								sx={{
									fontWeight: 800,
									color: "text.secondary",
									textTransform: "uppercase",
									letterSpacing: "0.1em",
								}}
							>
								Historical Growth Vector
							</Typography>
						</Box>
						<Box sx={{ height: 400, width: "100%" }}>
							<ResponsiveContainer width="100%" height="100%">
								<AreaChart data={history}>
									<defs>
										<linearGradient id="colorPop" x1="0" y1="0" x2="0" y2="1">
											<stop offset="5%" stopColor="#6366f1" stopOpacity={0.3} />
											<stop offset="95%" stopColor="#6366f1" stopOpacity={0} />
										</linearGradient>
									</defs>
									<CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(255,255,255,0.03)" />
									<XAxis dataKey="year" stroke="#475569" fontSize={11} fontWeight={700} tickLine={false} axisLine={false} tickSize={15} />
									<YAxis
										stroke="#475569"
										fontSize={10}
										fontWeight={700}
										tickLine={false}
										axisLine={false}
										tickFormatter={(val) => `${(val / 1000000).toFixed(0)}M`}
									/>
									<RechartsTooltip
										contentStyle={{
											backgroundColor: "#1e293b",
											borderRadius: "16px",
											border: "1px solid rgba(255,255,255,0.1)",
											boxShadow: "0 20px 25px -5px rgba(0,0,0,0.5)",
											padding: "12px 16px",
										}}
										itemStyle={{
											color: "#fff",
											fontWeight: 900,
											fontSize: "14px",
										}}
										labelStyle={{
											color: "#94a3b8",
											fontWeight: 800,
											fontSize: "11px",
											textTransform: "uppercase",
											marginBottom: "4px",
										}}
										formatter={(value) => [value.toLocaleString(), "CITIZENS"]}
									/>
									<Area type="monotone" dataKey="population" stroke="#6366f1" strokeWidth={4} fillOpacity={1} fill="url(#colorPop)" animationDuration={2000} />
								</AreaChart>
							</ResponsiveContainer>
						</Box>
					</Card>
				</Grid>

				<Grid item xs={12} lg={4}>
					<Card sx={{ p: 4, height: "100%", borderRadius: 8 }}>
						<Box sx={{ display: "flex", alignItems: "center", gap: 2, mb: 4 }}>
							<Box
								sx={{
									p: 1,
									borderRadius: 2,
									bgcolor: "rgba(244, 63, 94, 0.2)",
									display: "flex",
								}}
							>
								<Newspaper size={20} color="#fb7185" />
							</Box>
							<Typography variant="h6" sx={{ fontWeight: 800 }}>
								Regional Briefings
							</Typography>
						</Box>
						<Box sx={{ height: 420, overflowY: "auto", pr: 1 }}>
							{news.map((item, idx) => (
								<Box
									key={idx}
									component="a"
									href={item.url}
									target="_blank"
									rel="noopener noreferrer"
									sx={{
										display: "block",
										p: 2.5,
										mb: 2,
										borderRadius: 4,
										bgcolor: "rgba(255,255,255,0.03)",
										border: "1px solid transparent",
										textDecoration: "none",
										transition: "all 0.3s",
										"&:hover": {
											bgcolor: "rgba(255,255,255,0.06)",
											borderColor: "rgba(255,255,255,0.1)",
											transform: "translateX(4px)",
										},
									}}
								>
									<Box
										sx={{
											display: "flex",
											justifyContent: "space-between",
											alignItems: "center",
											mb: 1,
										}}
									>
										<Typography
											variant="caption"
											sx={{
												fontWeight: 900,
												color: "primary.light",
												textTransform: "uppercase",
												letterSpacing: "0.1em",
											}}
										>
											{item.source}
										</Typography>
										<Typography variant="caption" sx={{ color: "text.disabled", fontWeight: 700 }}>
											{item.date}
										</Typography>
									</Box>
									<Typography
										variant="subtitle2"
										sx={{
											fontWeight: 800,
											color: "white",
											mb: 1,
											lineClamp: 2,
											display: "-webkit-box",
											WebkitLineClamp: 2,
											WebkitBoxOrient: "vertical",
											overflow: "hidden",
										}}
									>
										{item.title}
									</Typography>
									<Typography
										variant="body2"
										sx={{
											fontSize: "0.7rem",
											color: "text.secondary",
											fontStyle: "italic",
											lineClamp: 2,
											display: "-webkit-box",
											WebkitLineClamp: 2,
											WebkitBoxOrient: "vertical",
											overflow: "hidden",
										}}
									>
										"{item.description}"
									</Typography>
								</Box>
							))}
							{!news.length && (
								<Box sx={{ textAlign: "center", py: 10 }}>
									<Typography
										sx={{
											color: "text.disabled",
											fontWeight: 800,
											textTransform: "uppercase",
											fontSize: "0.75rem",
											letterSpacing: "0.1em",
										}}
									>
										Intelligence Unavailable
									</Typography>
								</Box>
							)}
						</Box>
					</Card>
				</Grid>
			</Grid>
		</Container>
	);
}
